using AutoMapper;
using FutureConnection.Core.DTOs;
using FutureConnection.Core.Entities;
using FutureConnection.Core.Interfaces.Infrastructure;
using FutureConnection.Core.Interfaces.Repositories;
using FutureConnection.Core.Utils;
using Microsoft.AspNetCore.Http;

namespace FutureConnection.IdentityService.Application
{
    public class UserService(IUnitOfWork uow, IMapper mapper, IPasswordHasher passwordHasher, IMediaService mediaService, IEventPublisher eventPublisher) : IUserService
    {
        private readonly IUnitOfWork _uow = uow;
        private readonly IMapper _mapper = mapper;
        private readonly IPasswordHasher _passwordHasher = passwordHasher;
        private readonly IMediaService _mediaService = mediaService;
        private readonly IEventPublisher _eventPublisher = eventPublisher;

        public async Task<Response<UserDto>> AddExtraUserInfo(UpdateUserDto updateUserDto)
        {
            var user = await _uow.Users.GetByIdAsync(updateUserDto.Id);
            if (user == null) return new Response<UserDto> { Success = false, Message = "User not found" };

            // FIX: actually apply the DTO fields to the user entity
            if (!string.IsNullOrEmpty(updateUserDto.FirstName)) user.FirstName = updateUserDto.FirstName;
            if (!string.IsNullOrEmpty(updateUserDto.LastName)) user.LastName = updateUserDto.LastName;
            if (!string.IsNullOrEmpty(updateUserDto.Email)) user.Email = updateUserDto.Email;
            if (updateUserDto.SocialMediaId.HasValue) user.SocialMediaId = updateUserDto.SocialMediaId;

            _uow.Users.Update(user);
            await _uow.CompleteAsync();
            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        public async Task<Response<bool>> CheckUserId(Guid userId)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            return new Response<bool> { Data = user != null, Success = true };
        }

        public async Task<Response<bool>> CheckEmail(string email)
        {
            var exists = await _uow.Users.CheckEmail(email);
            return new Response<bool> { Data = exists, Success = true };
        }

        public async Task<Response<bool>> DeleteUser(Guid userId)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            if (user == null) return new Response<bool> { Success = false, Message = "User not found" };
            await _uow.Users.SoftDeleteAsync(user.Id);
            await _uow.CompleteAsync();
            return new Response<bool> { Data = true, Success = true };
        }

        public async Task<Response<IEnumerable<UserDto>>> GetAllUsers()
        {
            var users = await _uow.Users.GetAllAsync();
            return new Response<IEnumerable<UserDto>> { Data = _mapper.Map<IEnumerable<UserDto>>(users), Success = true };
        }

        public async Task<Response<UserDto>> GetUser(Guid userId)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            if (user == null) return new Response<UserDto> { Success = false, Message = "User not found" };
            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        public async Task<Response<UserDto>> GetUserByEmail(string email)
        {
            var user = await _uow.Users.GetUserByEmail(email);
            if (user == null) return new Response<UserDto> { Success = false, Message = "User not found" };
            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        public async Task<Response<UserDto>> GetUserByPhoneNumber(string phoneNumber)
        {
            var user = await _uow.Users.GetUserByPhoneNumber(phoneNumber);
            if (user == null) return new Response<UserDto> { Success = false, Message = "User not found" };
            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        /// <summary>
        /// Validates user credentials and updates last login info.
        /// Returns the user's profile data. The actual JWT is generated by AuthService.
        /// </summary>
        public async Task<Response<UserDto>> Login(LoginUserDto loginDto)
        {
            var user = await _uow.Users.GetUserByEmail(loginDto.Email);
            if (user == null)
                return new Response<UserDto> { Success = false, Message = "Invalid email or password" };

            if (!_passwordHasher.VerifyPassword(loginDto.Password, user.HashedPassword))
                return new Response<UserDto> { Success = false, Message = "Invalid email or password" };

            user.LastLoginIp = loginDto.IpAddress;
            user.LastLoginDate = DateTime.UtcNow;
            _uow.Users.Update(user);
            await _uow.CompleteAsync();

            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        private static string? ValidatePasswordStrength(string password)
        {
            if (password.Length < 8) return "Password must be at least 8 characters.";
            if (!password.Any(char.IsUpper)) return "Password must contain at least one uppercase letter.";
            if (!password.Any(char.IsDigit)) return "Password must contain at least one digit.";
            return null;
        }

        public async Task<Response<UserDto>> Register(CreateUserDto registerDto)
        {
            if (await _uow.Users.CheckEmail(registerDto.Email))
                return new Response<UserDto> { Success = false, Message = "Email already exists" };

            var passwordError = ValidatePasswordStrength(registerDto.Password);
            if (passwordError != null) return new Response<UserDto> { Success = false, Message = passwordError };

            var user = _mapper.Map<User>(registerDto);
            user.HashedPassword = _passwordHasher.HashPassword(registerDto.Password);
            user.RoleId = registerDto.RoleId;

            await _uow.Users.CreateAsync(user);
            await _uow.CompleteAsync();

            // Publish UserCreatedEvent so ProfileService can auto-initialize the user's profile
            await _eventPublisher.PublishAsync("identity.events", new UserCreatedEvent
            {
                UserId = user.Id,
                Email = user.Email,
                FirstName = user.FirstName,
                LastName = user.LastName,
                RegisteredAt = DateTime.UtcNow
            });

            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        public async Task<Response<UserDto>> UpdateUser(UpdateUserDto updateUserDto)
        {
            var user = await _uow.Users.GetByIdAsync(updateUserDto.Id);
            if (user == null) return new Response<UserDto> { Success = false, Message = "User not found" };

            // Ensure new email is not taken by another user
            if (!string.IsNullOrEmpty(updateUserDto.Email) && updateUserDto.Email != user.Email)
            {
                if (await _uow.Users.CheckEmail(updateUserDto.Email))
                    return new Response<UserDto> { Success = false, Message = "Email is already in use by another account." };
            }

            if (!string.IsNullOrEmpty(updateUserDto.FirstName)) user.FirstName = updateUserDto.FirstName;
            if (!string.IsNullOrEmpty(updateUserDto.LastName)) user.LastName = updateUserDto.LastName;
            if (!string.IsNullOrEmpty(updateUserDto.Email)) user.Email = updateUserDto.Email;
            if (updateUserDto.SocialMediaId.HasValue) user.SocialMediaId = updateUserDto.SocialMediaId;

            _uow.Users.Update(user);
            await _uow.CompleteAsync();
            return new Response<UserDto> { Data = _mapper.Map<UserDto>(user), Success = true };
        }

        public async Task<Response<string>> UpdateAvatarAsync(Guid userId, IFormFile file)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            if (user == null) return new Response<string> { Success = false, Message = "User not found" };

            var uploadResult = await _mediaService.UploadMediaAsync(file);
            if (uploadResult == null) return new Response<string> { Success = false, Message = "Failed to upload image" };

            // We could optionally delete the old avatar from Cloudinary here if we stored the PublicId
            user.AvatarUrl = uploadResult.Url;

            _uow.Users.Update(user);
            await _uow.CompleteAsync();

            return new Response<string> { Success = true, Data = user.AvatarUrl, Message = "Avatar updated successfully" };
        }

        public async Task<Response<string>> ChangePasswordAsync(Guid userId, string currentPassword, string newPassword)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            if (user == null) return new Response<string> { Success = false, Message = "User not found" };

            if (!_passwordHasher.VerifyPassword(currentPassword, user.HashedPassword))
                return new Response<string> { Success = false, Message = "Incorrect current password" };

            var passwordError = ValidatePasswordStrength(newPassword);
            if (passwordError != null) return new Response<string> { Success = false, Message = passwordError };

            if (_passwordHasher.VerifyPassword(newPassword, user.HashedPassword))
                return new Response<string> { Success = false, Message = "New password must be different from your current password." };

            user.HashedPassword = _passwordHasher.HashPassword(newPassword);
            _uow.Users.Update(user);
            await _uow.CompleteAsync();
            return new Response<string> { Success = true, Message = "Password changed successfully" };
        }

        public async Task<Response<bool>> MarkEmailVerifiedAsync(Guid userId)
        {
            var user = await _uow.Users.GetByIdAsync(userId);
            if (user == null) return new Response<bool> { Success = false, Message = "User not found" };
            user.IsEmailVerified = true;
            _uow.Users.Update(user);
            await _uow.CompleteAsync();
            return new Response<bool> { Success = true, Data = true };
        }

        public async Task<Response<bool>> LogoutAsync(Guid userId, string token)
        {
            if (!string.IsNullOrEmpty(token))
            {
                await _uow.BlacklistedTokens.CreateAsync(new BlacklistedToken
                {
                    Token = token,
                    ExpiryDate = DateTime.UtcNow.AddHours(2),
                    Reason = "User Logout"
                });

                // REVOKE Refresh Tokens: Find all active ones for this user and kill them
                var activeTokens = (await _uow.RefreshTokens.GetAllAsync())
                                    .Where(rt => rt.UserId == userId && rt.IsActive);
                
                foreach (var rt in activeTokens)
                {
                    rt.IsRevoked = true;
                    rt.RevokedAt = DateTime.UtcNow;
                    _uow.RefreshTokens.Update(rt);
                }

                await _uow.CompleteAsync();
            }
            return new Response<bool> { Success = true, Data = true };
        }
    }
}
